import './css/style.css'
import './css/topbar.css'
import './css/navbar.css'
import './css/hero.css'
import './css/features.css'
import './css/about.css'
import './css/programs.css'
import './css/enrollment.css'
import './css/contact.css'
import './css/footer.css'

import './ts/navbar'
import './ts/programs'
import './ts/enrollment-select'
import './ts/enrollment-form'
